# Generated by Django 5.2.7 on 2025-12-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=128)),
                ('owner_id', models.BigIntegerField()),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('scene', 'Scene'), ('object', 'Object'), ('op', 'Operation')], max_length=16)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'project_entities',
                'indexes': [models.Index(fields=['project_id', 'entity_type'], name='project_ent_project_f5bb53_idx')],
                'unique_together': {('project_id', 'entity_id')},
            },
        ),
    ]
