# Generated by Django 5.2.7 on 2025-12-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectentity',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='projectentity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_entities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
