# Generated by Django 6.0 on 2025-12-28 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectentity_owner_id_projectentity_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_id', models.UUIDField(db_index=True)),
                ('object_id', models.CharField(max_length=128)),
                ('materials', models.JSONField()),
            ],
            options={
                'unique_together': {('scene_id', 'object_id')},
            },
        ),
    ]
