# Generated by Django 6.0 on 2025-12-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_scenematerial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SceneMaterial',
        ),
    ]
